import { NextResponse } from "next/server"

const posts = [
  {
    id: 1,
    author: "John Doe",
    username: "@johndoe",
    content: "Having a great time at the beach! 🏖️ #vacation",
    timestamp: "2023-09-25T10:30:00Z",
    likes: 102,
    comments: 15,
    shares: 8,
  },
  {
    id: 2,
    author: "Alice Smith",
    username: "@alice.smith",
    content: "Just finished reading a fantastic book. Highly recommended! 📚",
    timestamp: "2023-09-24T15:45:00Z",
    likes: 56,
    comments: 7,
    shares: 3,
  },
  {
    id: 3,
    author: "Ella Johnson",
    username: "@ella123",
    content: "Cooking up a storm in the kitchen today! 🍳👩‍🍳 #cheflife",
    timestamp: "2023-09-23T18:20:00Z",
    likes: 78,
    comments: 10,
    shares: 5,
  },
  {
    id: 4,
    author: "David Wilson",
    username: "@davidwilson",
    content: "Enjoying the beautiful sunset view. Nature is amazing! 🌅",
    timestamp: "2023-09-22T20:15:00Z",
    likes: 92,
    comments: 12,
    shares: 6,
  },
  {
    id: 5,
    author: "Emily Brown",
    username: "@emilyb",
    content: "Excited for the weekend getaway with friends! 🚗🏞️ #roadtrip",
    timestamp: "2023-09-21T12:05:00Z",
    likes: 120,
    comments: 18,
    shares: 9,
  },
  {
    id: 6,
    author: "Michael Lee",
    username: "@michaellee",
    content: "Just started a new coding project. Can't wait to see it come to life! 💻🚀",
    timestamp: "2023-09-20T09:00:00Z",
    likes: 45,
    comments: 5,
    shares: 2,
  },
  {
    id: 7,
    author: "Sophia Davis",
    username: "@sophiad",
    content: "Spent the day exploring art galleries. So much creativity! 🎨",
    timestamp: "2023-09-19T14:30:00Z",
    likes: 68,
    comments: 11,
    shares: 4,
  },
  {
    id: 8,
    author: "Liam Miller",
    username: "@liamm",
    content: "Sunday morning workout. Feeling energized! 💪🏋️‍♂️",
    timestamp: "2023-09-18T08:45:00Z",
    likes: 88,
    comments: 9,
    shares: 3,
  },
  {
    id: 9,
    author: "Olivia White",
    username: "@oliviawhite",
    content: "Celebrating a friend's birthday tonight! 🎉🎂 #partytime",
    timestamp: "2023-09-17T21:00:00Z",
    likes: 75,
    comments: 14,
    shares: 6,
  },
  {
    id: 10,
    author: "Noah Turner",
    username: "@noaht",
    content: "Just adopted a new puppy! 🐶 Meet Max! #newpuppy",
    timestamp: "2023-09-16T17:10:00Z",
    likes: 110,
    comments: 20
  }
]

export async function GET(){
  return NextResponse.json(posts)
}