import Nav from "../../components/Nav";
import AuthProvider from "./AuthProvider";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "300", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Social-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Nav />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
